version: "2"
services:
  server:
    build: .
    ports:
      - "3000:3000"
      - "5000:5000"
    environment:
        MONGODB_URI:
        mongodb://localhost:27017/maalka_bedes
    links:
      - mongodb
  mongodb:
    image: mongo
