version: "2"
services:
  client:
    container_name: bedes_client
    build: './client'
    ports:
      - "3000:3000"

  server:
    container_name: bedes_server
    build: .
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: mongodb://mongo/maalka_bedes
    links:
        - mongo

  mongo:
    container_name: mongodb
    image: mongo
