version: "2"
services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/maalka_bedes
    links:
      - mongo

  mongo:
    image: mongo
