version: "2"
services:
  app:
    container_name: maalka_bedes
    restart: always
    build: .
    ports:
      - "3000:3000"
      - "5000:5000"
    environment:
      MONGODB_URI: mongodb://mongo/maalka_bedes
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
